# Generated by Django 3.2.15 on 2022-11-24 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modify_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modify_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion_producto', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Costo de Producto')),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor de Venta de Producto')),
                ('cantidad_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Cantidad Disponible')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modify_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.subcategoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
